package output

import (
	"fmt"
	"strings"
	"time"

	"github.com/BATAHA22/mapstr/internal/graph"
	"github.com/BATAHA22/mapstr/internal/parser"
)

// GenerateMarkdown produces the CONTEXT.md content.
// If aiSummary is empty (--no-ai mode), it generates a structural-only summary.
func GenerateMarkdown(projectName string, nodes []*parser.FileNode, g *graph.DependencyGraph, aiSummary string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Project: %s\n\n", projectName)

	if aiSummary != "" {
		b.WriteString(aiSummary)
	} else {
		writeStructuralSummary(&b, nodes, g)
	}

	b.WriteString("\n\n---\n\n")
	fmt.Fprintf(&b, "*Generated by [Mapstr](https://github.com/BATAHA22/mapstr) on %s*\n",
		time.Now().Format("2006-01-02 15:04:05"))

	return b.String()
}

func writeStructuralSummary(b *strings.Builder, nodes []*parser.FileNode, g *graph.DependencyGraph) {
	languages := map[string]int{}
	totalFuncs := 0
	totalTypes := 0
	totalRoutes := 0
	var entryPoints []string

	for _, n := range nodes {
		languages[n.Language]++
		totalFuncs += len(n.Functions)
		totalTypes += len(n.Types)
		totalRoutes += len(n.APIRoutes)

		if isEntryPoint(n.Path) {
			entryPoints = append(entryPoints, n.Path)
		}
	}

	b.WriteString("## Overview\n\n")
	fmt.Fprintf(b, "This project contains **%d files** across **%d languages**.\n\n", len(nodes), len(languages))

	b.WriteString("| Language | Files |\n|----------|-------|\n")
	for lang, count := range languages {
		fmt.Fprintf(b, "| %s | %d |\n", lang, count)
	}

	b.WriteString("\n## Architecture\n\n")
	fmt.Fprintf(b, "- **%d** functions/methods\n", totalFuncs)
	fmt.Fprintf(b, "- **%d** types/classes\n", totalTypes)
	fmt.Fprintf(b, "- **%d** API routes\n", totalRoutes)
	fmt.Fprintf(b, "- **%d** module dependencies\n", len(g.Edges))

	if len(entryPoints) > 0 {
		b.WriteString("\n## Entry Points\n\n")
		for _, ep := range entryPoints {
			fmt.Fprintf(b, "- `%s`\n", ep)
		}
	}

	if totalRoutes > 0 {
		b.WriteString("\n## API Routes\n\n")
		b.WriteString("| Method | Path | File |\n|--------|------|------|\n")
		for _, n := range nodes {
			for _, route := range n.APIRoutes {
				fmt.Fprintf(b, "| %s | %s | %s |\n", route.Method, route.Path, n.Path)
			}
		}
	}

	// List key exported types
	var exportedTypes []string
	for _, n := range nodes {
		for _, t := range n.Types {
			if t.Exported {
				exportedTypes = append(exportedTypes, fmt.Sprintf("`%s` (%s in %s)", t.Name, t.Kind, n.Path))
			}
		}
	}

	if len(exportedTypes) > 0 {
		b.WriteString("\n## Key Types\n\n")
		for _, t := range exportedTypes {
			fmt.Fprintf(b, "- %s\n", t)
		}
	}
}

func isEntryPoint(path string) bool {
	lower := strings.ToLower(path)
	patterns := []string{
		"main.go", "main.py", "index.js", "index.ts",
		"app.go", "app.js", "app.ts", "app.py",
		"server.go", "server.js", "server.ts", "server.py",
	}
	for _, p := range patterns {
		if strings.HasSuffix(lower, p) {
			return true
		}
	}
	return strings.Contains(lower, "cmd/")
}
